### ISSUE TITLE
Configuration improvement

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/smart-testing#106]
We are having way too many properties which we could pass as part of the build format. This is convenient as a supplement to override some defaults, but we should rethink how we configure our tool. 

We should have one config file in place where we can specify all required bits. This way we enable teams to share this configuration as a part of their code rather then shell script with properties or documentation (README). By introducing config file we also gain easy integration with other tools like IDEs.

Before we break it down to tasks let's discuss the format and use cases.

**Comment by bartoszmajsak** [comment]
I was thinking about simple YAML file to start with, for example

```yaml
mode: ordering
strategies: 
  - new
  - changed
  - affected
```

I'm not sure about git/scm properties as these are rather used in combination with variables from CI, for example `$ mvn clean verify -Dsmart.testing=new, affected -Dgit.commit=GIT_COMMIT -Dgit.previous.commit=GIT_PREVIOUS_COMMIT`

**Comment by dipak-pawar** [comment]
> I was thinking about simple YAML file to start with:
```yaml
mode: ordering
strategies: 
  - new
  - changed
  - affected
```
Maybe we could think about adding `disable` too.

> I'm not sure about git/scm properties as these are rather used in combination with variables from CI, for example `$ mvn clean verify -Dsmart.testing=new, affected -Dgit.commit=GIT_COMMIT -Dgit.previous.commit=GIT_PREVIOUS_COMMIT`

I think this is no required now. 

> Having such a files would also imply that if we have found it in the root folder we enable our tool.
This, however, raises next question: what if we allow having per-module files too? Is it something useful? I could think of using different strategies for different kind of tests which most likely sit in the different modules of the project.

We can do like this, if sub-module has configuration file then use it, otherwise look for configuration file in parent module

**Comment by MatousJobanek** [comment]
>  By introducing config file we also gain easy integration with other tools like IDEs.

yeah, exactly. Based on the file I can create a window where users can specify every property. 

> I was thinking about simple YAML file to start with

I'm fine with the YAML file. As for the properties - yeah this is a good start - as the next ones would be:

```yaml
affected:
    inclusion:
        - org.package.*
        - org.arquillian.package.*
    exclusions:
        - org.package.exclude.*
        - org.arquillian.package.exclude.*
```
In other words, any system property that is supported in ST should have a place also in the config file, and vice versa. As you can see, the level reflect words after dots in system properties: `smart.testing.affected.inclusions`

> what if we allow having per-module files too? Is it something useful?

+1 I would definitely support per-module config files
Another thing is if we should also support something like profiles or files for different usages - I can imagine that in various cases different configuration should be used - eg. in travis, or when you run the build on your PC locally. Or do not bother with the profiles/multiple files and just use the system properties to overwrite that ones in the file....?

Another thing comes to my mind related to IDE & config file - If the config window in Che is used, then should I change the file accordingly, or should that be something that is stored in Che memory? By default, I would use Che memory, but I would allow (by using check-box) to write the changes also into the config file.

**Comment by lordofthejars** [comment]
My question is should we have one YAML file to configure all of them, or each strategy might have its own file?

**Comment by MatousJobanek** [comment]
> one YAML file to configure all of them

+1

**Comment by hemanik** [comment]
I also like the idea of putting all ST related configuration in one YAML file keeping aside git related properties.
> We can do like this, if sub-module has configuration file then use it, otherwise look for configuration file in parent module.

Also, I like dipak's idea of not making it mandatory to have a config file per module.

**Comment by bartoszmajsak** [comment]
> We can do like this, if sub-module has configuration file then use it, otherwise look for configuration file in parent module.

What if some things are not configured in the sub-module? Defaults or looking up what's in the parent?

**Comment by bartoszmajsak** [comment]
> > Another thing is if we should also support something like profiles or files for different usages - I can imagine that in various cases different configuration should be used - eg. in travis, or when you run the build on your PC locally. Or do not bother with the profiles/multiple files and just use the system properties to overwrite that ones in the file....?

I would simply override through property pointing to another file. My experience from Maven world is that profiles are getting messy and hard to reason about very fast.

> Or can we have a forge like tool to generate a YAML file for us, if system properties are provided ?

@hemanik How can this be helpful for the user? Can you shed some more light on your idea? I was thinking that config file would be the way for the user to configure everything. Properties would become exceptional means of overwriting something.

**Comment by hemanik** [comment]
Having all the configuration stored in file like YAML, makes it easier to check and even debug in case of failure.
If configuration is set as system properties and overridden, we will lose it from YAML. (So, in my opinion, we should also override the YAML file and have a single point of reference.)
Also, adding config-file for each module could become tedious. Sometimes, it's more convenient to fire a single command with tab-completion.    
My thought was if could have a CLI command to generate a YAML for us. 

For example: User specifies the module-name/path, mode, and strategy and a YAML for it is generated in the root of the module path. (even better if we could use something like tab-completion for mode and strategy).

**Comment by MatousJobanek** [comment]
Good idea @hemanik.  Having command-line tool for editing/creating config files makes sense for complicated/complex ones such as `standalone.xml` in wildfly. I'm afraid that in our case it would be an overkill.

**Comment by MatousJobanek** [comment]
In other words, IMHO it is not necessary to create such a command-line tool.

**Comment by dipak-pawar** [comment]
We can do like this, if sub-module has configuration file then use it, otherwise look for configuration file in parent module.

> @dipak-pawar What if some things are not configured in the sub-module? Defaults or looking up what's in the parent?

@bartoszmajsak I would vote for defaults, if no configuration file in submodule, disable smart-testing.

Having said that I would provide some option to exclude sub-module in parent smart-testing configuration file to disable `smart-testing` i..e `use defaults`, so this way user is not forced to use smart-testing for all sub-modules, he can exclude any sub-module

Another thing is if user has very big(100) multi-module project where he may wants to use 10 different smart testing configuration, so he has to copy same configuration file in different modules where he want to apply that same configuration for smart testing. 

For this we can provide way in parent file to define all smart testing configuration in one place where user can define all sub-modules for which he wants to use same configuration. So no duplicates.
