### ISSUE TITLE
Ability to fetch all git changes at once

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/smart-testing#11]
Currently when fetching git changes for affected strategy we have to call both new and changed git detections. This results in calling the same git logic twice. We should introduce lower level component letting us get this information all at once.

**Comment by lordofthejars** [comment]
In partial solution we have added a composition of both strategies into one _util_ class: https://github.com/arquillian/smart-testing/blob/master/strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/AllChangedFilesDetector.java Now we still have the problem that git repository is opened twice, but from the client perspective it is only one call. We need to profile that and decide if we want a full refactor of the solution or we can leave it as is.

**Comment by bartoszmajsak** [comment]
Related to #44

**Comment by lordofthejars** [comment]
I think this can be closed as maven extension work is on master. cc/ @bartoszmajsak

**Comment by bartoszmajsak** [comment]
Fixed with refactorings in #57
