### ISSUE TITLE
Introduce per-module configuration file

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/smart-testing#114]
Add ability to overwrite configuration defined by root `smart-testing.yaml` file within each project module.

**Current assumption**: we require to have a file in the root folder as an enabler for our tool.

- [x] implement precedence logic
- [ ] update documentation (In Progess)
- [x] add ability for `Test Bed` to define per-module configuration (and at adjust at least one existing test)

**Comment by bartoszmajsak** [comment]
Requires #113 to be in place

**Comment by lordofthejars** [comment]
Not directly related with this issue, but something to have in mind. Here we are talking all the time about having configuration per module, but I see another level and it is been able to create files with suffix in each of the module. For example in case of local development you might want to run with selecting mode meanwhile in ci/cd in ordering mode.

I know that you can change this property using a system property but this affects gloably, so having something like:

`smart-testing.yml` this is always loaded then you can have `smart-testing-commit-stage.yml` and if and only if a property called `stage` is set to `commit-stage`, data of `smart-testing.yml` is overriden by the one from `smart-testing-commit-stage.yml`.

**Comment by bartoszmajsak** [comment]
Maybe we can have a way of defining a sequence of files with the precedence instead (and some reasonable default?). Maybe even activation on a property?

**Comment by lordofthejars** [comment]
The problem is that maybe someone wants 3 different kind of configurations others 2 others 5, so I think that make it as generic as possible is the best way. So the sequence is `smart-testing.yml` and if property set `smart-testing-xxx.yml`. So it is the user who defines the suffix.

**Comment by bartoszmajsak** [comment]
That's exactly what I had mind.

**Comment by lordofthejars** [comment]
Sorry to not understand you at first 😆

**Comment by MatousJobanek** [comment]
- [ ] create `inherit` parameter that will point to either absolute or relative path (working transitively)
  * if there is no inheritance then the file should be valid
  * if there is no file in submodule, look for the project (submodule) parent config file
- [ ] use `disable` parameter only as a local param - no look-up

```
parent
 - config
   - smart-testing.yml -inherits-> parent/smart-testing.yml
   -- api
   -- impl-base
   -- spi
     - smart-testing.yml
 - container
    -- container-api
    -- containerl-impl
 - smart-testing.yml
```
if I run from `parent` then it should use the `parent/config/smart-testing.yml` for both `api` `impl-base`, but for `spi` it will use that one from the `spi` directory
