### ISSUE TITLE
Should not register extension if skipTests is configured in pom.xml

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#142]
**pom.xml**

Properties:
```xml
<properties>
        <skipTests>true</skipTests>
</properties>
```
Surefire plugin configuration:
```xml
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
      <skipTests>${skipTests}</skipTests>  
    </configuration>
</plugin>
```

With this configuration If user is trying to run tests with smart testing enabled. Then `ST` extension should not register.

Currently we are only looking for system properties `maven.test.skip` or `skipTests`. We should look for pom.xml configuration

**Comment by hemanik** [comment]
dependencies
￼dependencies
￼
+ add dependency
￼ dipak-pawar added Component: Maven Type: Bug Priority: Medium labels 8 days ago
￼
+ add dependency
￼ dipak-pawar added Component: Maven Type: Bug Priority: Medium labels 8 days ago
￼
