### ISSUE TITLE
There should be one logic/api that takes care of all files to be stored during/after test execution

### ISSUE THREAD

**Issue by MatousJobanek** [arquillian/smart-testing#157]
Extend/Change `LocalStorage` class to have two options/methods:
* `duringExecution` - to store files nedded (storable) only during execution - in `${base.dir}/.smart-testing` directory
* `afterExecution`- to store files to be persisted also when the test finishes - in `${base.dir}/target/smart-testing`

`duringExecution` has two options:
* `temporary` - containing temporary/working files that will be removed after the build finishes (currently it is named `execution` but I would change it not to confuse with the `duringExecution` name)
* `reporting` - containing report related files - after the test execution, the dir will be copied to `${base.dir}/target/smart-testing` 

`afterExecution` has only one - `reporting` which is the very same directory as that one from the previous part with the difference, that it is immediately stored in the target dir.

The usage the looks like:
to store scm changes:
```java
new LocalStorage(currentDirectory)
                .duringExecution()
                .temporary()
                .file(SMART_TESTING_SCM_CHANGES);
```

to store report:
```java
new LocalStorage(baseDir)
                .afterExecution()
                .reporting()
                .file(REPORT_FILE_NAME);
```

As you know - choosing the class/method names is one of my weaknesses :-). If you have some better names, I'm open for any change.

**Comment by MatousJobanek** [comment]
This can be also considered as an attempt to prepare local storage for one API that will take care of both - storing locally and in a cloud. That is also the reason why I'm trying to make it unified across the whole project.

**Comment by bartoszmajsak** [comment]
Good idea @MatousJobanek. We need to start improving the code base.

the chain of methods is a bit unclear for me, so I would propose a slight change: how about changing`reporting()` into `toReporting()`?
