### ISSUE TITLE
Should not fail If committed changes has deleted file

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#160]
##### Issue Overview
Currently we are only looking for `ADD` & `MODIFY` [ChangeType](https://github.com/arquillian/smart-testing/blob/master/core/src/main/java/org/arquillian/smart/testing/scm/ChangeType.java#L5) 

While extracting committed changes [here](https://github.com/arquillian/smart-testing/blob/master/core/src/main/java/org/arquillian/smart/testing/scm/git/GitChangeResolver.java#L145) we should look for `DELETE` OR `RANAMED` ChangeType & filter it later if not interested.  

##### Expected Behaviour
ST should work fine with deleted test file.

##### Current Behaviour
ST is failing with exception 
```java
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalArgumentException: No enum constant org.arquillian.smart.testing.scm.ChangeType.DELETE
```

##### Steps To Reproduce
1. Clone this reproducible [project](https://github.com/dipak-pawar/ST_reproducer)
2. Run tests using cmd
``` bash
mvn clean test -Dsmart.testing=new,changed,affected -Dscm.range.head=HEAD -Dscm.range.tail=HEAD~3
```
Note: I haven't tested this for `RENAMED` ChangeType. Please test this as well. I believe this will also fail.

**Comment by bartoszmajsak** [comment]
Hah, good find :)

**Comment by bartoszmajsak** [comment]
I will commit a quick fix for enum compatibility but we have to address other concerns you pointed out in order to complete this issue.

**Comment by bartoszmajsak** [comment]
A bit of digging reveals interesting behaviour of JGit, which I guess is a bug (probably related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=434085)

From CLI (on the `repo.bundle` coming with the PR):
```shell
git diff --no-commit-id --name-status 6b4a8a3..76b6069
R085	strategies/changed/src/test/java/org/arquillian/smart/testing/vcs/git/DummyFilesDetectorTest.java	strategies/changed/src/test/java/org/arquillian/smart/testing/vcs/git/EvenMoreDummyFilesDetectorTest.java
```

but jgit results in:

```java
0 = {DiffEntry@1633} "DiffEntry[DELETE strategies/changed/src/test/java/org/arquillian/smart/testing/vcs/git/DummyFilesDetectorTest.java]"
1 = {DiffEntry@1634} "DiffEntry[ADD strategies/changed/src/test/java/org/arquillian/smart/testing/vcs/git/EvenMoreDummyFilesDetectorTest.java]"
```
