### ISSUE TITLE
NPE is thrown is strategy is mispelled

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/smart-testing#167]
##### Issue Overview

NPE is thrown if you set a strategy incorrectly

##### Expected Behaviour

Throw a meaningful exception instead of NPE.

##### Current Behaviour

NPE

**Comment by bartoszmajsak** [comment]
> Did you mean this instead of that

Good idea, we could use https://en.wikipedia.org/wiki/Levenshtein_distance to find the closest match.

In addition, we can automatically change to the closest match, like we can do with git
`git config help.autocorrect 1`, but this can be done as a follow-up task

**Comment by bartoszmajsak** [comment]
Broke it down to two issues. Follow-up with  suggestion #170
