### ISSUE TITLE
.smart-testing folder is not removed if JVM is stopped

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/smart-testing#168]
##### Issue Overview

`.smart-testing` folder is not removed if JVM is stopped by using `Ctrl+C` during test phase.

##### Expected Behaviour

Folder should be removed

##### Current Behaviour

Folder is not removed

**Comment by bartoszmajsak** [comment]
We can simply add `Runtime.getRuntime().addShutdownHook()` to support `Ctrl+C`.

**Comment by bartoszmajsak** [comment]
Cannot reproduce using projects from Test Bed. Are you sure it's `Ctrl+C` which stops your JVM?

**Comment by lordofthejars** [comment]
I was stopping the build with ctrl C all the time, maybe this was not the
stimilus

**Comment by bartoszmajsak** [comment]
No, it was my mistake - hence I deleted the comment
