### ISSUE TITLE
Add support to provide option `-Dgit.lastcommits=no_of_commits` to run tests.

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#17]
Currently we have to run tests using `mvn -Dgit.previous.commit=$PREV_COMMIT -Dgit.commit=$COMMIT clean test`

along with this add support to run tests using `mvn -Dgit.lastcommits=3 clean test`

So calculate all required commit using current HEAD with number of commits given in `git.lastcommits` property from HEAD.

**Comment by bartoszmajsak** [comment]
Technically speaking you don't have to calculate anything, just use `HEAD^no`

**Comment by MatousJobanek** [comment]
Is there some default value? When I don't specify any commit...?
I would guess that if I have some local not-committed changes, then it takes the diff with HEAD. Otherwise HEAD..HEAD^ (one commit back)

**Comment by lordofthejars** [comment]
Yes this is how it works

**Comment by bartoszmajsak** [comment]
> Is there some default value? When I don't specify any commit...?

All is in the code :) https://github.com/arquillian/smart-testing/blob/1b30f1e70b77ce24e58aa4e75c6c35c215cfe170/strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/ChangedFilesDetectorFactory.java#L21-L23

**Comment by bartoszmajsak** [comment]
> I would guess that if I have some local not-committed changes, then it takes the diff with HEAD. Otherwise HEAD..HEAD^ (one commit back)

One commit back
