### ISSUE TITLE
Shaded extension doesn't work with older versions of Maven

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/smart-testing#175]
##### Issue Overview

Following the guide, I copied shaded extension (`maven-lifecycle-extension-0.0.1-shaded.jar`) into `M2_HOME/lib/ext`, but when running the build nothing happens (no sign of extension in the logs).

##### Expected Behaviour

The extension is working after installing it by [following the guide](http://arquillian.org/smart-testing/#_maven_3_1_x).

##### Current Behaviour

No signs of extension kicking in (nothing in the logs).

##### Steps To Reproduce

1. Change Maven to version pre `3.3.x`
2. Download extension from [Maven Central](http://central.maven.org/maven2/org/arquillian/smart/testing/maven-lifecycle-extension/0.0.1/maven-lifecycle-extension-0.0.1-shaded.jar)
3. Copy to `M2_HOME/lib/ext`
4. Run the build using e.g. `mvn clean package -Dsmart.testing=new,changed -Dsmart.testing.mode=selecting`

##### Additional Information

```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /usr/share/maven/apache-maven-3.2.5
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_144/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.12.9-300.fc26.x86_64", arch: "amd64", family: "unix"
arquillian-core [mvn --version]
```

**Comment by bartoszmajsak** [comment]
So we have to decide, either we treat it as high prio and ship fix soon enough, or we revise the docs.

**Comment by lordofthejars** [comment]
I think that the easiest and most used way by users would be to just drop support for versions prior to 3.3.X for now.

**Comment by MatousJobanek** [comment]
Do you have any idea what could be the problem? It can be just a simple bug, but can be also a little bit more complex. How about time-box it for several hours and if it seems to be more complex, then I would drop support for the older version...

**Comment by bartoszmajsak** [comment]
My idea for dropping is temporary - we just release `0.0.2` with all the fixes and say that older versions are not supported yet. And then we can timebox to analyze. WDYT?

**Comment by lordofthejars** [comment]
:+1:

**Comment by bartoszmajsak** [comment]
https://github.com/jcgay/maven-profiler
