### ISSUE TITLE
NPE in SmartTestingProviderTests when executing from the IDE

### ISSUE THREAD

**Issue by hemanik** [arquillian/smart-testing#179]
##### Issue Overview

Smart testing provider tests return NPE when provider invocation not set or set to null.
 
##### Expected Behaviour

System property `basedir` should not be null.

##### Current Behaviour

System property `basedir` is not set.

##### Steps To Reproduce
1. Execute SmartTestingProviderTest `when_get_suites_is_called_then_same_list_of_classes_will_be_returned` and `test_when_invoke_is_called_with_null` from Intellij

**Comment by bartoszmajsak** [comment]
@hemanik Are these the only tests failing in IDE?
