### ISSUE TITLE
Classes under src/main with name contains `test` in not excluding due to which tests are failing with exception.

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#19]
We are filtering our glassed with globePattern which contains following matchingPattern
* `**/Test*.java`
* `**/*Test.java`
* `**/*TestCase.java`
 * `**/*$*`

If user has some class inside src/main/java/ `org/arquillian/smart/testing/surefire/provider/TestExecutionPlannerLoader.java` which is not test class, our smart testing should filter it, as it's not a test class.

But currently it is not filtering it & we are getting exception as `initializationError  java.lang.Exception: No runnable methods`.

**Comment by lordofthejars** [comment]
We faced this problem, for now we are fixing using https://github.com/arquillian/smart-testing/pull/14/files#diff-196256830d61c29176bbc3b577307a56R46

**Comment by dipak-pawar** [comment]
How about adding filtering inside our code when we have all changed classes, we can easily filter only test classes instead of asking user to add `<includes>` in surefire configuration explicitly?

**Comment by dipak-pawar** [comment]
@lordofthejars you can it here #20 for my proposed solution for this
