### ISSUE TITLE
Test should run successfully, if we are running tests from one module, there are some changed files in another module 

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#21]
If we have multi-module project 
- module A
- module B
maven surefire is configured to module B as follows:
```xml
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${version.surefire}</version>
        <configuration>
          <properties>
            <orderStrategy>new,changed</orderStrategy>
          </properties>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.arquillian.smart.testing</groupId>
            <artifactId>smart-testing-surefire-provider</artifactId>
            <version>${project.version}</version>
          </dependency>
        </dependencies>
      </plugin>
```

If I ran tests from module B using `mvn -Dgit.previous.commit=$PREV_COMMIT -Dgit.commit=$COMMIT clean test -pl module-B` 

Now after changing some tests from module A, If I try to run tests using above command again. Our smart-testing-tool should not worry about module-A change.

Currently getting exception ClassNotFound which is right as this class is from different module. But out tests should continue instead of throwing exception. You can look code [here](https://github.com/arquillian/smart-testing/blob/master/surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/TestStrategyApplier.java#L28)

**Comment by bartoszmajsak** [comment]
That was my observation too. I believe we should solve it on the surefire integration level as that's the place where we have the knowledge about "modules" etc.

**Comment by dipak-pawar** [comment]
:+1:
