### ISSUE TITLE
Should not register ST extension if user is trying to run it with project which doesn't have scm repository setup

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#216]
##### Issue Overview
If your project doesn't have scm repository. `mvn clean test` is failing due to couldn't initialize `GitChangeResolver`

##### Expected Behavior
ST extension should not be registered if project doesn't have `SCM` repository.

##### Current Behavior
Getting exception as
``` bash
Exception in thread "main" java.util.ServiceConfigurationError: org.arquillian.smart.testing.scm.spi.ChangeResolver: Provider org.arquillian.smart.testing.scm.git.GitChangeResolver could not be instantiated
```
##### Steps To Reproduce
1. Create simple project where you can apply smart testing. 
2. Run smart testing with required configuration.

**Comment by MatousJobanek** [comment]
> ST extension should not be registered if project doesn't have SCM repository.

the extension can be registered - failing strategy can be still used, just the strategies that need the scm information cannot be used
