### ISSUE TITLE
Smart Testing should run with project which has SCM setup, but doesn't have single commit

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#217]
##### Issue Overview
Smart testing should not fail if user is trying to run test with Smart Testing in project which doesn't have single commit.

##### Expected Behavior
ST should be smart enough to determine there is not even single commit. Consider all changes as local & apply test optimization if any.

##### Current Behavior
Getting exception as `org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalArgumentException: Commit id 'HEAD~0' is not found in /home/dipak/test-team/configuration-file-demo/.git Git repository`

##### Steps To Reproduce
1. Create simple project to which you want to apply Smart Testing.
2. Install smart testing extension using `curl -sSL https://git.io/v5jy6 | bash  ` 
2. Do scm setup using `git init`
3. Run test using `mvn clean test -Dsmart.testing.strategies=new`

Note: Due to this user can't execute any maven lifecycle goal like(`mvn clean`) as it's failing with some exception in smart testing extension before reaching to other maven lifecycle

**Comment by MatousJobanek** [comment]
nice catch!
The behavior would be same as for: https://github.com/arquillian/smart-testing/issues/216 - there should be some error printed on the console containing that the scm information is not available and some strategies cannot be used.
