### ISSUE TITLE
NoSuchMethodError  `ProviderParameters.getConsoleLogger()` with surefire 2.20.1

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#218]
##### Issue Overview
If you are trying to run test with surefire version `2.20.1` with current master, it throwing exception without running tests.

It runs fine with surefire `2.19.1`

##### Expected Behavior
Test should run fine with Smart testing enabled.

##### Current Behavior
Getting exception as 
```bash
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] java.lang.NoSuchMethodError: org.apache.maven.surefire.providerapi.ProviderParameters.getConsoleLogger()Lorg/apache/maven/surefire/report/ConsoleLogger;
```

##### Steps To Reproduce
1. Clone https://github.com/dipak-pawar/configuration-file-demo
2. Install Smart testing snapshot with latest master using `mvn clean install -DskipTests` from smart testing code base 
2. Execute `mvn clean test` 

##### Additional Information
```
 Apache Maven 3.3.9 (NON-CANONICAL_2016-04-07T23:15:34Z_mockbuild; 2016-04-08T04:45:34+05:30)
Maven home: /usr/share/maven
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /opt/jdk1.8.0_101/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.7.9-200.fc24.x86_64", arch: "amd64", family: "unix"
</details>
```

**Comment by dipak-pawar** [comment]
I am not sure if this has something to do with #201

**Comment by hemanik** [comment]
Yes @dipak-pawar , It's related to #201.

**Comment by MatousJobanek** [comment]
yeah, it is the same issue, so I'm closing this as a duplication of https://github.com/arquillian/smart-testing/issues/201
