### ISSUE TITLE
Should delete target directory completely for mvn clean if configuration file has debug true enabled

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#219]
##### Issue Overview
Currently there is no way to maven extension to check which lifecycle of maven user is trying to execute. Due to which extension is trying to install all required dependency/modification of pom.xml even in `clean, compile` phase.

Now consider this scenario:
You have `smart-testing.yml` is defined as configuration file which has debug enabled in it
```yaml
mode: selecting
strategies: new
debug : true
``` 
Now if user is trying to execute `mvn clean` then as per maven convention it should delete target directory.
But as we are purging all the required reports/effective-poms in `afterSessionEnd` method. It's not deleting target directory because it has purged effective-pom.xml in 
`smart-testing/smart-testing-effective-pom.xml`
This should not be the case for `mvn clean`

##### Expected Behaviour
`mvn clean` should delete target directory completely

##### Current Behaviour
`mvn clean` is keeping purged resources in target directory 

##### Steps To Reproduce
1. Run smart testing using `mvn clean test` on any project with following content for `smart-testing.yml`
```yaml
mode: selecting
strategies: new
debug : true
``` 
2. Again run `mvn clean`
3. Look for `target` directory inside your project & it's content

**Comment by MatousJobanek** [comment]
There is a way to check the specified goals. Unfortunately, this case is more complicated than just the `clean` goal. You can also run `mvn compile` and the tests are not executed. etc...
