### ISSUE TITLE
Getting NPE if providing empty smart-testing.yml

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#248]
*Steps To Reproduce*
* Create empty config file `smart-testing.yml` in project's root dir.
* Run test with `mvn test`

*Actual Result*
Getting NPE 

*Expected Result*
We should get appropriate msg if config file is empty

**Comment by lordofthejars** [comment]
What is happening if the file is empty but all system properties are set? Then it should not fail, it is just that you have an empty scaffold

**Comment by dipak-pawar** [comment]
> What is happening if the file is empty but all system properties are set? Then it should not fail, it is just that you have an empty scaffold

@lordofthejars If you are creating `smart-testing.yml` then it should have some content/properties. It should fail. what is the point to creating empty file
