### ISSUE TITLE
Overwrite missing/default configuration parameter from project's root configuration file

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#261]
Currently we are looking for configuration file recursively in it's parent till maven project root dir.

With this approach we are taking either entire or none configuration from that directory. We are not overwriting missing parameter from configuration defined in upper directory.

With this approach it's easy for a user to find all configuration in one place. But then user has to write same configuration again. So too much duplication.

***Proposed solution:***
Ask user to define all required smart testing configuration parameters in project's root `smart-testing.yml`. So if any parameter is missing/default, we'll overwrite it with configuration defined in project's root. We don't have to check any other upper directory to overwrite loaded configuration(either from current dir or it's parent dir)
In this way project's root `smart-testing.yml` is mandatory to enable smart-testing excluding scenario where we are setting system property `smart.tesing=new,chnaged`(In other words it's not mandatory if user set this system property)

another point is user can define all global properties like scm configuration here only. So we can find respective Scm Changes according to root config

With this approach user can find configuration details in config file location & project's root config file.

Thoughts?

**Comment by bartoszmajsak** [comment]
> With this approach we are taking either entire or none configuration from that directory. We are not overwriting missing parameter from configuration defined in upper directory.

Why are we doing it this way now? I thought we were always considering hierarchical lookup, but not on the file level, but property level. Like we do with system properties. Did I miss something here?

**Comment by dipak-pawar** [comment]
I didn't think for this with single configuration file. Now we have multiple configuration files(per module) So I can imagine pain for users.

But We are considering considering hierarchical lookup like `system property -> file -> default`. It's not like `system property -> file -> it's parent recursively till project root -> default`.

**Comment by bartoszmajsak** [comment]
Ok my misunderstanding then, wouldn't it be better to just implement #114 first instead?

**Comment by dipak-pawar** [comment]
I am almost done with it. Will submit PR soon.

**Comment by bartoszmajsak** [comment]
Great, but then do we need to even consider this one at all?

**Comment by dipak-pawar** [comment]
yes we need to consider it to avoid duplication while writing config file for user

**Comment by MatousJobanek** [comment]
I thought that this should be part of the #114 issue

**Comment by bartoszmajsak** [comment]
I think that is the whole idea behind #114. So that you can have only partial configuration in modules which is specific to it and the rest is defined up in the chain. So the lookup for a given property looks like this (going up in the chain until defined):

`module-file` -> ..... -> `module-file` -> `root config`

Or taking it straight for env vars, if it's defined there.

**Comment by dipak-pawar** [comment]
Addressing this as a part of #114. Details here: https://github.com/arquillian/smart-testing/issues/114#issuecomment-343438869
