### ISSUE TITLE
Add @Resource-like annotation in affected tests.

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/smart-testing#263]
##### Issue Overview

Currently affected tests annotations only allows you to set a hard dependency with classes. For example:

```
@ComponentUnderTest(packages = "org.arquillian.smart.testing.strategies.affected.fakeproject.main.superbiz.*")
public class ZTest {
```

But would be great to add an annotation to allow specify "configuration" files as well. For example if a test must be run if `persistence.xml` file is modified or `kubernetes.json`.

For this reason I purpose to have some annotation for example called `@Resource` (with also its `@Repeatable` annotation) where you can set this can of relationship.

For example:

```
@Resource("src/main/resources/persistence.xml")
public class CarDaoTest {}
```

So if `src/main/resources/persistence.xml"` is changed then `CarDaoTest` is run too.

**Comment by bartoszmajsak** [comment]
`@Resource` might be misleading here... because it's a very broad term. How about `@WatchFile` or something better indicating that change in such a file will trigger a test.

**Comment by lordofthejars** [comment]
Sure for this reason I said in the title `@Resource-like` because as you said it is really bad name.
