### ISSUE TITLE
Categorized strategy properties are not being recognized when using a configuration file

### ISSUE THREAD

**Issue by spriadka** [arquillian/smart-testing#318]
##### Issue Overview

Properties from configuration file are not getting mapped into the `categorized` strategy configuration.

##### Expected Behaviour

When running smart testing with the `categorized` strategy and a configuration file, smart testing should configure the `categorized` strategy from configuration file correctly. 

##### Current Behaviour

When running smart testing with `categorized` strategy and a configuration file, properties set in that file are not being recognized by the execution itself. According to the `report.xml` smart testing sees only, that the categorized strategy has been applied, but all the properties are ignored.
```xml
 <executionConfiguration>
        <usageMode>selecting</usageMode>
        <strategies>
            <strategy>categorized</strategy>
        </strategies>
        <properties>
            <property name="smart.testing" value="categorized"/>
        </properties>
    </executionConfiguration
```
Running smart testing with properties set as command line arguments are recognized properly.

##### Steps To Reproduce
1. Clone this repository https://github.com/spriadka/testsuite/tree/7.1.x-categories
2. Set up the machine according to the README
3. Create `smart-testing.yml` following:
``` yaml
strategies: categorized
debug: true
strategiesConfiguration:
  categorized:
    categories: Elytron
```
4. Execute following command 
```bash
mvn -Pbasic,standalone -Djboss.dist=<your_jboss_dist> -Darq.extension.webdriver.firefox_binary=<your_ff_binary_path> -Dtest="ElytronPolicyTestCase*" test
```
5. See the `basic/target/.smart-testing/report.xml`

**Comment by MatousJobanek** [comment]
Hi @spriadka 
thank you for reporting this issue. This is caused by improper lazy loading of the configuration files.
This should fix the issue: https://github.com/arquillian/smart-testing/pull/319
