### ISSUE TITLE
Unify logging

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/smart-testing#33]
It seems that other Surefire providers use `stdout` for `INFO` and `stderr` for WARN logging (https://github.com/arquillian/smart-testing/pull/31#issuecomment-305127074). We have JUL in few places in the code already. We should unify the usage across the project based on [new logger](https://github.com/arquillian/smart-testing/blob/d606c8ccb7481e5ed810aaabe2b68265ee957995/surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SmartTestingProviderLogger.java) introduced in #31.

**Comment by MatousJobanek** [comment]
I'm not sure if we can unify it across the whole project - the stdout and stderr logging doesn't provide us any possibility to log on a lower level (DEBUG, FINEST,..).
We have probably two possibilities:
1. Use the SmartTestingProviderLogger.java only in provider and in other modules use JUL as it is done now. 
2. extend logic of SmartTestingProviderLogger.java so in a case of INFO and WARN use stdout and stderr, for all other levels use JUL. As a result, there will be one logger class that would hide that he is using two different ways of logging. This will also require moving the SmartTestingProviderLogger.java
class to core.

I would vote for the second option. WDYT?

**Comment by bartoszmajsak** [comment]
Variant 2 makes much more sense. Thanks for thinking it through. 

Two additional things I can think of here:

  * We should rename the class - maybe `Logger` is enough here?
  * What about class info when using JUL? If we move it to common class we would end up with `.getLogger(this.getClass())`. This way we are loosing an information about to source of the log.

**Comment by MatousJobanek** [comment]
Yes, both of your comments is a must.
I chose the name as my first intention was to use it only in the provider. And the class info when using JUL is really essential.

**Comment by bartoszmajsak** [comment]
> I chose the name as my first intention was to use it only in the provider. And the class info when using JUL is really essential.

I know :) Just pointing it out that if we move it we might want to change it.
