### ISSUE TITLE
Clarify/fix behavior when a concrete set of test classes is specified

### ISSUE THREAD

**Issue by MatousJobanek** [arquillian/smart-testing#39]
When I specify `-Dtest=SomeTest`, I use `testAll=false`, and the test doesn’t fall into the selection, then what we should do? Currently, it doesn't run anything I guess, but the expected behavior would be that the test is run. Right?

**Comment by bartoszmajsak** [comment]
Good catch! Thanks @MatousJobanek.

> Currently, it doesn't run anything I guess.

Can we make sure what is the actual behaviour at the moment?

## Proposed solution 

I think `-Dtest=SomeTest` or any other way where you instruct a test runner to run certain tests should mean that the test will be executed regardless. There are several possibilities to instrument `surefire` about which test(s) should be executed by using `-Dtest` flag. We can run selected test, multiple tests, tests matching patterns and so on. [More details can be found in the examples](http://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html). 

I believe we should stick to following:

  * if the test falls into the categories it will be selected anyway (nothing to do here)
  * if the test doesn't fall into any of the categories it should be run at the end - appended to the prioritized list

Based on the examples linked above we should prepare acceptance criteria / tests for it too.

**Comment by bartoszmajsak** [comment]
Let's investigate if that is still the case with the latest implementation and evaluate if the proposed solution is feasible.

**Comment by hemanik** [comment]
@Matous, are there any specific tests that you are talking about here (like functional-tests) ? 

Today, I tried executing the normal unit tests in the smart-testing repo and my observation is as follows:
- when the test is executed as `mvn surefire:test -Dtest=StrategyDependencyResolverTest` with plugin, everything works as expected.
- but when the test is executed as `mvn -Dtest=StrategyDependencyResolverTest test`, an error message as follows is encountered.
```
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project smart-testing-maven-lifecycle-extension: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.) 
```
 Is this issue described here, or am I missing something ?

**Comment by hemanik** [comment]
When `-Dtest` property is set, Maven `TestsToRun` class only includes the set of tests included in `test` property. If this test set has tests common to those filtered by our strategy they are executed and if it is a disjoint set none are executed in case of `selecting` mode and the specified test-set is executed in case of `ordering` mode.

Do we need to fix this functionality ? 

In my opinion, as per the `test` property's intended behavior the user only wishes to select a subset of the tests and if these fit under our criteria as per different strategies these get executed, if not then it is ignored.
So, then the current implementation works.

But if we want to add the use-case that the user should be able to execute the selected subset of tests irrespective of or over and above our strategy, then we'll have to extend this functionality.

**Comment by MatousJobanek** [comment]
Sorry for my late response.

> @MatousJobanek , are there any specific tests that you are talking about here (like functional-tests) ?

no, tests in general.

> In my opinion, as per the test property's intended behavior the user only wishes to select a subset of the tests and if these fit under our criteria as per different strategies these get executed, if not then it is ignored.
So, then the current implementation works.

From my point of view, If I use the property -Dtest=MyCoolTest then I want to run the test regardless of what is set in ST configuration. 

In other words, If a user sets any list of test classes, then we should disable ST extension. And also appropriately log the behavior - that ST tool is disabled and why.
