### ISSUE TITLE
Seamlessly store test results from the build execution

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/smart-testing#47]
`failed` strategy relies on historical build execution. At this point we only support local experience. It has an assumption that reports from previous test run are stored in the `.report` folder. We don't have however any automated way of getting those reports there other than user doing it manually.

This task should automate this process in the `surefire-provider`. Every test result file should be moved to this folder.  We should also purge the folder **after** we gather test results data from the previous build, as we will write new ones. I'm open here to other ideas though, as this is suboptimal. Maybe subfolder per build would be better?

We should also implement it such that plugging in publisher of test reports to the "hub" would be a matter of adding it as a dependency. Good candidate for SPI?

**Comment by bartoszmajsak** [comment]
Should we make the location folder configurable as part of this story or a follow-up one?

**Comment by lordofthejars** [comment]
We can do it in this issue. Also when you say `purge` you mean based on created time, make a configurable strategy, ....

**Comment by bartoszmajsak** [comment]
> based on created time, make a configurable strategy 

I think we are going to far. I would just say "clean",

Well just realized it should be **after** the build.

**Comment by bartoszmajsak** [comment]
Another question here would be how do we want to store this data in the long run. Is the `junit-xml` format sufficient enough? Can we just generate stubs based on the [junit-xsd](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) and use it as a part of our solution? Especially considering transferring it over the wire? Or do we want to have our own structure tailored to our needs? What that would mean in terms of supporting stuff beyond surefire?

**Comment by MatousJobanek** [comment]
Another area to investigate is getting the information (to be stored) using Surefire/JUnit/TestNg API - using `RunResult` object that we [get in the provider](https://github.com/arquillian/smart-testing/blob/master/surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/SmartTestingSurefireProvider.java#L64):
and/or [JUnit](http://junit.org/junit4/javadoc/4.12/org/junit/runner/notification/RunListener.html)/[Surefire](https://github.com/apache/maven-surefire/blob/master/surefire-api/src/main/java/org/apache/maven/surefire/report/RunListener.java) listeners

As for local storing - I would do it in similar way as Surefire does for its ordering - have one file that changes during the builds

**Comment by dipak-pawar** [comment]
Few options to think:
- Store only failed build results or all?
- Store only last build execution result or `n` subsequent build execution result.
