### ISSUE TITLE
Rethink groupdId and artifactId

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/smart-testing#5]
We should rethink our naming strategy, e.g.: `org.arquillian.smart.testing:smart-testing-strategy-affected` is a bit too verbose.

**Comment by lordofthejars** [comment]
Or even dropping arquillian name? Or we want to create a relationship so Arquillian means everything related with tests?

**Comment by bartoszmajsak** [comment]
That will depend on how we will name it. Dropping this will force us to request permission to release it in central, but sure :)

**Comment by bartoszmajsak** [comment]
We stick with the name.
