### ISSUE TITLE
Git properties

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/smart-testing#52]
We should rename git properties to make them easier to understand. Having `git.commit` and `git.previous.commit` does not clearly explain their purpose nor it's easy to guess. 

I would suggest following changes:

  * `git.commit` -> `scm.range.head`
  * `git.previous.commit` -> `scm.range.tail`
  * `git.last.commits` -> `scm.last.changes`

Thoughts?

**Comment by lordofthejars** [comment]
should it be `git.range....` or `scm.range....`
