### ISSUE TITLE
TestNG Tests in the dogfooding repo giving error when trying to run with specified mode.

### ISSUE THREAD

**Issue by hemanik** [arquillian/smart-testing#62]
##### Issue Overview

When executing TestNG tests in the dogfooding repo with Smart Testing provider, we get the following error, 
```
The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /tmp/junit3013285195732663576/smart-testing-dogfood-repo_HistoricalChangesAffectedTestsSelectionExecutionFunctionalTest_should_execute_all_tests_when_smart_testing_is_disabled_irrespective_of_strategy/testng/core && /usr/java/jdk1.8.0_60/jre/bin/java -jar /tmp/junit3013285195732663576/smart-testing-dogfood-repo_HistoricalChangesAffectedTestsSelectionExecutionFunctionalTest_should_execute_all_tests_when_smart_testing_is_disabled_irrespective_of_strategy/testng/core/target/surefire/surefirebooter3375551549339713544.jar /tmp/junit3013285195732663576/smart-testing-dogfood-repo_HistoricalChangesAffectedTestsSelectionExecutionFunctionalTest_should_execute_all_tests_when_smart_testing_is_disabled_irrespective_of_strategy/testng/core/target/surefire 2017-07-17T19-42-19_270-jvmRun1 surefire6725514113717898404tmp surefire_08997551454508629680tmp
Error occurred in starting fork, check output in log
```  
Here's the related issue: https://gist.github.com/juherr/6eb3e93e2db33979b7e90b63ddadc888

##### Expected Behaviour
Tests should execute as per the strategy and mode selected.

##### Current Behaviour
The output is as follows,
```
cat org.jboss.arquillian.testng.TestNGIntegrationTestCase-output.txt 
Configuring TestNG with: TestNG60Configurator
Cannot use a threadCount parameter less than 1; 1 > 0
Usage: <main class> [options] The XML suite files to run
  Options:
    -configfailurepolicy
       Configuration failure policy (skip or continue)
    -d
       Output directory
    -dataproviderthreadcount
       Number of threads to use when running data providers
    -excludegroups
       Comma-separated list of group names to  exclude
    -groups
       Comma-separated list of group names to be run
    -junit
       JUnit mode
       Default: false
    -listener
       List of .class files or list of class names implementing ITestListener or
       ISuiteListener
    -methods
       Comma separated of test methods
       Default: []
    -methodselectors
       List of .class files or list of class names implementing IMethodSelector
    -mixed
       Mixed mode - autodetect the type of current test and run it with
       appropriate runner
       Default: false
    -objectfactory
       List of .class files or list of class names implementing
       ITestRunnerFactory
    -parallel
       Parallel mode (methods, tests or classes)
       Possible Values: [tests, methods, classes, instances, none, true, false]
    -port
       The port
    -reporter
       Extended configuration for custom report listener
    -suitename
       Default name of test suite, if not specified in suite definition file or
       source code
    -suitethreadpoolsize
       Size of the thread pool to use to run suites
       Default: 1
    -testclass
       The list of test classes
    -testjar
       A jar file containing the tests
    -testname
       Default name of test, if not specified in suitedefinition file or source
       code
    -testnames
       The list of test names to run
    -testrunfactory, -testRunFactory
       The factory used to create tests
    -threadcount
       Number of threads to use when running tests in parallel
    -usedefaultlisteners
       Whether to use the default listeners
       Default: true
    -log, -verbose
       Level of verbosity
    -xmlpathinjar
       The full path to the xml file inside the jar file (only valid if -testjar
       was specified)
       Default: testng.xml
```
##### Steps To Reproduce
1. Change the pom.xml as https://github.com/hemanik/smart-testing-dogfood-repo/commit/aa0e855199e5a5f95298ed00c47217cc1672d3cb for the testng tests in dogfooding repo.
 2. Execute `mvn clean test -X -pl testng/core `

##### Environment Details

```
Apache Maven 3.3.9 (NON-CANONICAL_2016-04-07T23:15:34Z_mockbuild; 2016-04-08T04:45:34+05:30)
Maven home: /usr/share/maven
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_60/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.10.15-100.fc24.x86_64", arch: "amd64", family: "unix"
```

**Comment by bartoszmajsak** [comment]
Thanks for reporting @hemanik. According to the gist you shared it only happens when:

> when you have both `surefire-junit47` and `surefire-testng` as dependency.

@MatousJobanek can this be solved in the Surefire Provider itself? We pull in some dependency there, right?

**Comment by bartoszmajsak** [comment]
@hemanik In order to unblock your work you can exclude this module from the embedded build for your tests, having configuration equivalent to `mvn clean test -X -pl !testng/core` (if that's the only module).

@MatousJobanek is there such an option in embedded mvn? Couldn't find it by quickly looking at the API.

**Comment by dipak-pawar** [comment]
@bartoszmajsak we do have `setProjects` options which I believe @hemanik already using.

**Comment by bartoszmajsak** [comment]
It would be awesome to have an ability for exclusion as well. Doesn't seem like we can do it atm. Could you try to contribute this feature to upstream project?

**Comment by dipak-pawar** [comment]
sure, you mean if we hit this `mvn -pl '!core,!app1' clean install`, so it should exclude `core` & `app1` using maven embedded. but atm it's not excluding right?

**Comment by bartoszmajsak** [comment]
That's exactly what I mean. Did you try it out?

**Comment by MatousJobanek** [comment]
> can this be solved in the Surefire Provider itself? We pull in some dependency there, right?

Yeah, we pull - but it should pull only one provider, so it shouldn't happen that two providers are on classpath.


> is there such an option in embedded mvn? Couldn't find it by quickly looking at the API.

everything that is possible to set you can find here: https://github.com/shrinkwrap/resolver/blob/master/maven/api-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/embedded/pom/equipped/ConfigurationStage.java
technically, you could try to use: https://github.com/shrinkwrap/resolver/blob/master/maven/api-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/api/maven/embedded/pom/equipped/ConfigurationStage.java#L90

**Comment by bartoszmajsak** [comment]
I was more thinking about having list of excluded modules, so higher-level concept than list of exclude files for a reactor :)

**Comment by dipak-pawar** [comment]
> That's exactly what I mean. Did you try it out?

No I haven't tried

**Comment by dipak-pawar** [comment]
Hey I tried with for excluding submodule. We have to explicitly tell to use maven version > 3.2.1 using `.useMaven3Version()` api because Maven `3.2.1` has added this feature.

@hemanik You can use exclude testng modules using following code
```java
final BuiltProject build = embeddedMaven
                    .useMaven3Version("3.3.9")
                    .setProjects("!testng, !testng/core, !testng/container, !testng/standalone")
                    .setGoals(goals)
                    .setDebug(isMavenDebugOutputEnabled())
                    .setQuiet(disableQuietWhenAnyDebugModeEnabled() && quietMode)
                    .skipTests(false)
                    .setProperties(systemProperties)
                    .ignoreFailure()
                .build();
```


@bartoszmajsak I have tested this, it's excluding modules if you set maven version > 3.2.1. No need to contribute to upstream as it's already there

**Comment by bartoszmajsak** [comment]
Thanks for checking it out @dipak-pawar. I was thinking that maybe we could still have a method which has better meaning, for example
```java
 .excludeProjects("testng/core", "testng/container","testng/standalone")
```
but if it works the way you described above we are good for the time being.

**Comment by bartoszmajsak** [comment]
As it turned out using `.useMaven3Version("3.3.9")` on Travis won't work (and probably also in other setups as we run stuff in parallel). I introduced following improvement to have this feature enabled for travis:
https://github.com/arquillian/smart-testing/pull/65

**Comment by bartoszmajsak** [comment]
@hemanik can you provide details about your environment in the issue description?

**Comment by bartoszmajsak** [comment]
It also looks that it only affects `ordering` mode which till now we didn't have in `test-bed`. For selecting it's working fine, otherwise all the other tests would be already failing like crazy. Thanks for making one with the ordering mode!

**Comment by hemanik** [comment]
```
Apache Maven 3.3.9 (NON-CANONICAL_2016-04-07T23:15:34Z_mockbuild; 2016-04-08T04:45:34+05:30)
Maven home: /usr/share/maven
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_60/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.10.15-100.fc24.x86_64", arch: "amd64", family: "unix"
```

**Comment by MatousJobanek** [comment]
Hi,
the reason why it is failing only with the `ordering` mode is that the changes you perform on the repository don't create/modify any TestNG class - only JUnit class. This means that the `selective` mode doesn't test anything as there are no TestNG tests that would fulfill the `runOrder` strategies.

As for the failure itself - in short - it is a bug/shortcoming in Surefire plugin itself. I'll create an issue for it in Surefire and send a PR and link it here...

**Comment by MatousJobanek** [comment]
Anyway, even if it was fixed in the next release of surefire, then (if we wanted to support the older versions of surefire such as `2.19.1` and `2.20.0`) we would need to have a workaround for it - it should be quite easy, so I'll do it.

**Comment by MatousJobanek** [comment]
Surefire issue link: https://issues.apache.org/jira/browse/SUREFIRE-1398
PR: https://github.com/apache/maven-surefire/pull/160
I'll send the workaround for the issue tomorrow

**Comment by MatousJobanek** [comment]
Workaround: https://github.com/MatousJobanek/smart-testing/commit/653914cac313861b91e29006012211ca6c3e4caf
