### ISSUE TITLE
Determine strategy automatically with single dependency of strategy in classpaths

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#68]
Currently we have to provide `strategy` in surefire configuration with following option `<strategies>new</strategies>`

*OR*

with System properties with maven extension approach.

**Proposed Solution:**
* If there is only one dependency in classpaths from `smart-testing-strategy-affected`, `smart-testing-strategy-new`, `smart-testing-strategy-changed` then our tool should determine it & use strategy as per dependency without mentioning it in configuration or in System property.

* If classpaths contains multiple dependencies then our tool should read for properties from configuration or from system properties which is currently present.

**Comment by bartoszmajsak** [comment]
With the maven extension there is no need of specifying any dependencies, this is taken care of in the background by extension itself. With the old, explicit approach that would make more sense.

**Comment by dipak-pawar** [comment]
Hmm then I am closing this issue
