### ISSUE TITLE
Filter selected tests based on testsToRun first instead of filtering it in selectTests  method of TestStrategyApplier 

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/smart-testing#70]
##### Issue Overview

Currently we are filtering tests on TestsToRun in [TestStrategyApplier](https://github.com/arquillian/smart-testing/blob/master/surefire-provider/src/main/java/org/arquillian/smart/testing/surefire/provider/TestStrategyApplier.java#L57)

I believe we can improve it by filtering it little early on getTests of respective strategy. e.g. in [NewTestsDetector](https://github.com/arquillian/smart-testing/blob/mvn_ext/strategies/changed/src/main/java/org/arquillian/smart/testing/vcs/git/NewTestsDetector.java#L42)

It will definitely help in improving performace

**Comment by MatousJobanek** [comment]
This is what I was pointing out when I wanted to pass only tests that will be run (eg. here: https://github.com/arquillian/smart-testing/pull/51#issuecomment-314717910). 
And not only for `new` test strategy but for all `TestExecutionPlanner` implementation.

**Comment by bartoszmajsak** [comment]
This would only work for surefire though, we have to think how to model it properly so it will be useful not only for this use case.

**Comment by bartoszmajsak** [comment]
With [`TestVerifier`](https://github.com/arquillian/smart-testing/blob/b26a69a74b508670995b3528155f42652a2e6efd/core/src/main/java/org/arquillian/smart/testing/filter/TestVerifier.java) interface in place it's now possible.
