### ISSUE TITLE
Ordering process should take into account previous configuration/strategies

### ISSUE THREAD

**Issue by MatousJobanek** [arquillian/smart-testing#77]
`Test` - normal test
`CTest` - Changed test
`FTest` - Failed test
`CFTest` - changed and failed test

Consider this situation:
we use `-Dsmart.testing=changed, failed`
and we get this list of test classes to reorder:

`Test1, CTest1, CFTest1, FTest1, CTest2, Test2, CTest3, CFTest2`

After applying only the `changed` strategy, then the resulting set would be:

`CTest1, CFTest1, CTest2, CTest3, CFTest2, Test1, FTest1, Test2`

When we apply both strategies `changed, failed`, then the resulting set contains:

`CTest1, CFTest1, CTest2, CTest3, CFTest2, FTest1, Test1, Test2`

Which means that only `FTest1` is moved

What I would expect is that after the first ordering, the classes would be divided into two sets - the one containing classes that fall into the condition of the strategy and the rest - in the case of `changed`:

`[ CTest1, CFTest1, CTest2, CTest3, CFTest2 ]  [ Test1, FTest1, Test2 ]`

Then the ordering process for the second strategy would be applied on bots sets separately:

`[ [ CFTest1, CFTest2] [ CTest1, CTest2, CTest3 ] ]   [ [ FTest1 ]  [ Test1, Test2 ] ]`

So the very first classes that will be run are those that fall into the most strategies.

In an analogical way, I would take into account `runOrder` parameter in Surefire configuration. In case that user uses `alphabetical` order and for smart testing the strategy `new` then all classes in both sets should be in the alphabetical order:

`[ ANewTest, BNewTest, CNewTest ] [ ATest, BTest ]`

**Comment by dipak-pawar** [comment]
Currently it's not implemented by this way. One way to do is look for all possible combinations of strategies, & sort it on the index of combinations.

e.g. let's assume strategies  are `"changed", "failed", "new", "affected"`
then list of priorities would be like this
```
[ changed, failed, new, affected
changed, failed, new
changed, failed, affected
changed, failed
changed, new, affected
changed, new
changed, affected
changed
failed, new, affected
failed, new
failed, affected
failed
new, affected
new
affected ]
```

So we can sort TestSelection on strategies as it already has all strategies. WDYT? @bartoszmajsak , @MatousJobanek

**Comment by MatousJobanek** [comment]
I don't understand what you mean by that - what the implementation would look like. 
I was thinking something along those lines:
```java
List<SelectionPerCombinationOfStrategies> selectedTests = new ArrayList<>();
        strategies.forEach(strategyName -> {
            final TestExecutionPlanner plannerForStrategy = testExecutionPlannerLoader.getPlannerForStrategy(strategyName);
            Collection<TestSelection> tests = plannerForStrategy.getTests();

            selectedTests.forEach(selectionsPerStrategy -> {

                List<TestSelection> intersection = selectionsPerStrategy.getTestIntersection(tests);
                selectionsPerStrategy.getTestSelection().removeAll(intersection);
                tests.removeAll(intersection);

                ArrayList<String> newStrategyCombination = new ArrayList<>(selectionsPerStrategy.getStrategies());
                newStrategyCombination.add(strategyName);

                SelectionPerCombinationOfStrategies newCombination =
                    new SelectionPerCombinationOfStrategies(newStrategyCombination, intersection);
                selectedTests.add(selectedTests.indexOf(selectionsPerStrategy), newCombination);
            });

            if (!tests.isEmpty()){
                selectedTests.add(new SelectionPerCombinationOfStrategies(strategyName, new ArrayList<>(tests)));
            }
        });
```
The `SelectionPerCombinationOfStrategies` class then would store:
`List<String> strategies`
`List<TestSelection> testSelections`
Main benefit would be that you could store the information which strategy was applied on particular set of tests.
I wrote the code quickly and haven't tested (may contain a few bugs and doesn't have to be effective). But I believe that you will understand my intention.
