### ISSUE TITLE
NullPointerException is thrown when having custom surefire configuration

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/smart-testing#83]
##### Issue Overview

NullPointerException is thrown when having custom surefire configuration. For example:

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>2.19.1</version>
  <configuration>
    <forkCount>1</forkCount>
    <reuseForks>false</reuseForks>
  </configuration>
</plugin>
```

##### Expected Behaviour

Work normally

##### Current Behaviour

Null pointer exception is thrown.

##### Steps To Reproduce
1. Clone https://github.com/perwendel/spark
2. Install ST extension
3. `mvn -Dsmart.testing=changed -Dsmart.testing.mode=selecting clean test`

##### Additional Information

Using Maven 3.5.0 and Surefire version 2.19.1

**Comment by MatousJobanek** [comment]
To get the project with this configuration correctly working, you need to use these fixes:
https://github.com/arquillian/smart-testing/pull/84
https://github.com/arquillian/smart-testing/pull/85
https://github.com/arquillian/smart-testing/pull/87
and if you wanted to use the `2.20` version of the surefire plugin, you would need to use also this fix: https://github.com/arquillian/smart-testing/pull/86

**Comment by lordofthejars** [comment]
Great, then let's wait until we merge all of PRs to close it.
