### ISSUE TITLE
Transitivity in Affected strategy

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/smart-testing#98]
Currently Affected strategy just read the imports from the test class and uses this information to decide if given business class should be executed or not.

This means that if you have Test A that depends on  A class and this class at the same time depends on B class `ATest -> A -> B` and if the modified class is `B` then `ATest` is not executed.

Ideally affected strategy should also resolve transitive dependencies of business classes.

**Comment by lordofthejars** [comment]
After thinking a bit about how to limit the growth of the graph I though next rules:

* By default `smart.testing.depth.level` is equal to 5, I think that with this default we might cover a lot of cases, and this even more true in microservics world.
* By default `smart.testing.package.level` is 2. This means that package filtering is done by getting the two first elements of the test package and classes are filtered by these numbers.
* By default `smart.testing.package.exclusions` is empty.

Then last two options are exclusive so if `smart.testing.package.exclusions` is set, then `smart.testing.package.level` is ignored. And `smart.testing.package.exclusions` can receive a URL to a file containing all the exclusions in package form or a string in CSV form of exclusions package.

**Comment by MatousJobanek** [comment]
`smart.testing.package.exclusions` how about regex?
as for the defaults. well, why not... At first, I'd like to measure the impact of the levels on some big project. If there is a big difference between "5" vs "without limit" and similar...

**Comment by lordofthejars** [comment]
I thought about regexp, so you mean or file (with regexp) or directly regexp, I am concerned about performance

**Comment by bartoszmajsak** [comment]
Do we have any measures to be already concerned about the performance and have a real need to introduce things such as `smart.testing.depth.level` limitation?

Maybe it's better to have the code exercised against the full project/module, then measure and see where we could improve rather than starting with some heuristics which can seriously limit usefulness of our tool.

Package filtering will obviously help, but I am not so sure about the others, to be honest.

**Comment by lordofthejars** [comment]
Well I am thinking for example in a Spring application, in these cases that Spring has several thousands of classes interconnected, I think it might be some problems.

**Comment by bartoszmajsak** [comment]
I agree there will be "problems" - what I'm not sure about if what's proposed above is the solution. At least not yet.

**Comment by lordofthejars** [comment]
Well limiting the search tree for sure minimize the problem

**Comment by bartoszmajsak** [comment]
> Well limiting the search tree for sure minimize the problem

and the potential usefulness or in other words completeness of the related test search.

**Comment by lordofthejars** [comment]
Current implementation uses regexp-like expressions setting as inclusions or exclusions, having priority exclusions.

The properties to set are: `smart.testing.affected.exclusions` and `smart.testing.affected.inclusions` in CSV format i.e `org.mypackage.*, org.myotherpackage.MyClass`

Also you can set them as a file by using `smart.testing.affected.exclusions.file` and `smart.testing.affected.inclusions.file`

**Comment by lordofthejars** [comment]
Finally instead of having two properties to set inclusions and exclusions file, we opted for having for having one property called `smart.testing.affected.config` where you can set the file location of a properties file containing exclusions  and inclusions in csv.

Notice that `smart.testing.affected.exclusions` and `smart.testing.affected.inclusions` are appended to config values
